// Code generated by "stringer -type=AstKind"; DO NOT EDIT.

package main

import "strconv"

const _AstKind_name = "ASTNILASTSYMASTNUMASTUXASTBINASTMODULEASTASSASTDEF"

var _AstKind_index = [...]uint8{0, 6, 12, 18, 23, 29, 38, 44, 50}

func (i AstKind) String() string {
	if i < 0 || i >= AstKind(len(_AstKind_index)-1) {
		return "AstKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AstKind_name[_AstKind_index[i]:_AstKind_index[i+1]]
}
