// Code generated by "stringer -type=NodeKind"; DO NOT EDIT.

package main

import "strconv"

const _NodeKind_name = "NODENILNODENUMNODEASSNODESYMNODEMOD"

var _NodeKind_index = [...]uint8{0, 7, 14, 21, 28, 35}

func (i NodeKind) String() string {
	if i < 0 || i >= NodeKind(len(_NodeKind_index)-1) {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[i]:_NodeKind_index[i+1]]
}
