// Code generated by "stringer -type=Oper"; DO NOT EDIT.

package main

import "strconv"

const _Oper_name = "OPNILOPEQOPADDOPSUBOPMULOPDIVOPMODOPASS"

var _Oper_index = [...]uint8{0, 5, 9, 14, 19, 24, 29, 34, 39}

func (i Oper) String() string {
	if i < 0 || i >= Oper(len(_Oper_index)-1) {
		return "Oper(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Oper_name[_Oper_index[i]:_Oper_index[i+1]]
}
